# Generated by Django 5.2.5 on 2025-09-03 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdoctormapping',
            old_name='assigned_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='patientdoctormapping',
            old_name='assigned_by',
            new_name='created_by',
        ),
    ]
